# Generated by Django 3.2.7 on 2021-09-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='images/blog_page_imgs')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='images/blog_page_imgs')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='images/blog_page_imgs')),
                ('video', models.FileField(blank=True, null=True, upload_to='images/blog_page_video')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='images/contact_page_imgs')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='images/contact_page_imgs')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='images/page1_imgs')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='images/page1_imgs')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='images/page1_imgs')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='images/page1_imgs')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='images/service_page_imgs')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='images/service_page_imgs')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='images/service_page_imgs')),
                ('video', models.FileField(blank=True, null=True, upload_to='images/service_page_video')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='images/services_page_imgs')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='images/services_page_imgs')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
